### ISSUE TITLE
Failed to activate the custom-window-title package

### ISSUE THREAD

**Issue by cornelius-dol** [pixilz/custom-window-title#9]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.54.0 x64
**Electron**: 6.1.12
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [custom-window-title](https://github.com/pixilz/custom-window-title) package 1.0.4

### Stack Trace

Failed to activate the custom-window-title package

```
At Cannot read property 'nodeName' of undefined

TypeError: Cannot read property 'nodeName' of undefined
    at CommandLogger.logCommand (D:/lawrence/setting/windows/appdata/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:892846)
    at D:/lawrence/setting/windows/appdata/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:892168
    at Function.simpleDispatch (D:/lawrence/setting/windows/appdata/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:1190181)
    at Emitter.emit (D:/lawrence/setting/windows/appdata/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:1191622)
    at CommandRegistry.handleCommandEvent (D:/lawrence/setting/windows/appdata/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:350014)
    at CommandRegistry.dispatch (D:/lawrence/setting/windows/appdata/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:348857)
    at c:/data/lawrence/setting/.atom/init.js:13:47
    at Array.forEach (<anonymous>)
    at c:/data/lawrence/setting/.atom/init.js:13:14
    at Workspace.atom.workspace.onDidAddTextEditor (c:/data/lawrence/setting/.atom/init.js:36:5)
    at Workspace.observeTextEditors (D:/lawrence/setting/windows/appdata/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:429504)
    at Object.activate (/packages/custom-window-title/lib/custom-window-title.coffee:105:37)
    at Package.activateNow (D:/lawrence/setting/windows/appdata/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:3658881)
    at D:/lawrence/setting/windows/appdata/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:3658293
    at Package.measure (D:/lawrence/setting/windows/appdata/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:3655871)
    at D:/lawrence/setting/windows/appdata/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:3658153
    at new Promise (<anonymous>)
    at Package.activate (D:/lawrence/setting/windows/appdata/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:3658096)
    at PackageManager.activatePackage (D:/lawrence/setting/windows/appdata/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:383646)
    at D:/lawrence/setting/windows/appdata/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:916751
    at r (D:/lawrence/setting/windows/appdata/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:911357)
    at s (D:/lawrence/setting/windows/appdata/Local/atom/app-1.54.0/resources/app/static/<embedded>:14:1121307)
    at ChildProcess.<anonymous> (D:/lawrence/setting/windows/appdata/Local/atom/app-1.54.0/resources/app/static/<embedded>:14:1121513)
    at ChildProcess.emit (events.js:200:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
```

### Commands

```
  2x -2:36.9.0 key-binding-resolver:toggle (input.hidden-input)
     -2:32.7.0 settings-view:open (input.hidden-input)
     -2:21.9.0 core:confirm (input.hidden-input)
     -2:17.5.0 editor:move-to-first-character-of-line (input.hidden-input)
     -2:15.2.0 editor:select-to-next-word-boundary (input.hidden-input)
  2x -2:14.7.0 core:delete (input.hidden-input)
  2x -2:14 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
autosave-onchange 1.5.1 
block-comment 0.4.3 
ctrl-dir-scroll 0.2.5 
custom-window-title 1.0.4 
grammar-token-limit 0.1.1 
justright-latte-syntax 0.1.0 
justright-latte-ui 0.1.0 
language-batchfile 0.7.5 
language-ini 1.23.0 
magic-reflow 0.3.0 
multi-cursor-plus 1.2.0 
no-title-bar 1.11.9 
overtype-ii 1.0.0 
process-palette 0.17.0 
project-manager 3.3.8 
sort-lines 0.19.0 
sync-settings 5.2.6 
tree-view-sort 0.12.1 
```

**Comment by cornelius-dol** [comment]
Appears to have been resolved.
